# Generated by Django 6.0.1 on 2026-01-29 20:48

import django.db.models.deletion
import qa_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=qa_app.models.answer_file_path, verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_files', to='qa_app.question', verbose_name='Вопрос')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл ответа',
                'verbose_name_plural': 'Файлы ответов',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=qa_app.models.question_file_path, verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='qa_app.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Файл вопроса',
                'verbose_name_plural': 'Файлы вопросов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
